spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC

jwt.secret =${JWT_SECRET}bda1d178f577db9d76994b5913f6ff5ac5a7413c681957334211e7e85502a93c
jwt.expiration =${JWT_EXPIRATION}86400000
jwt.email-verification-expiration =${JWT_EMAIL_VERIFICATION_EXPIRATION}86400000
jwt.reset-token-expiration =${JWT_RESET_TOKEN_EXPIRATION}900000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0bdf0da846a90a
spring.mail.password=abb7d1bea414d5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
token.api.email=bb565169caed3404b6f063bfd6e33e50
server.port=8080
logging.level.com.devarena=DEBUG